Implement Book Model and CRUD Operations with RSpec Tests.
Natali-Kotelnitska/web_library pull request #1
Opened 2023-10-12 18:15 UTC by Natali-Kotelnitska

Changes Made
1.  Book Model Implementation:
   - added the 'Book' model with CRUD operations.
   - implemented model validations.
   - integrated Faker and FactoryBot for generating realistic test data.

2. RSpec Tests:
   - developed RSpec tests to cover the CRUD operations on the 'Book' model.
   - installed 'shoulda-matchers' gem for testing validation and model.
   - verified that the test suite is running successfully.

2023-10-29 15:02 UTC, loqimean requested changes

2023-10-29 15:02 UTC, loqimean commented on app/controllers/application_controller.rb
> +  add_flash_types :error, :warning, :info
не бачу в цій строці сенсу

2023-10-29 15:02 UTC, loqimean commented on app/controllers/application_controller.rb
> +  add_flash_types :error, :warning, :info
для чого тобі це?

2023-10-29 15:02 UTC, loqimean commented on app/controllers/books_controller.rb
> +    flash.now[:warning] = "We have exactly #{@books.size} books available."
не тре цього

2023-10-29 15:02 UTC, loqimean commented on app/controllers/books_controller.rb
> +      render :new, status: :unprocessable_entity
```suggestion
      flash.now[:error] = "Error: Book could not be created."

      render :new, status: :unprocessable_entity
```

2023-10-29 15:02 UTC, loqimean commented on app/controllers/books_controller.rb
> +      render :edit, status: :unprocessable_entity
```suggestion
      flash.now[:error] = "Error: Book could not be created."

      render :edit, status: :unprocessable_entity
```

2023-10-29 15:02 UTC, loqimean commented on app/controllers/books_controller.rb
> +    @book.destroy
```suggestion
    @book = resource

    @book.destroy
```

2023-10-29 15:02 UTC, loqimean commented on app/views/books/_book.html.erb
> +  <% end %>
ця штука не гуд, окремо має бути для шоу паршал і окремо для індекса, бо інакше у тебе цей паршал з часом буде заповнений іфами

2023-10-29 15:02 UTC, loqimean commented on app/views/books/_form.html.erb
> +<%= simple_form_for @book,  url: (@book.new_record? ? books_path : book_path(@book)), defaults: { input_html: { class: 'form_input' } }, html: { class: 'contents' } do |form| %>
навіщо перевірка ця в шляху

2023-10-29 15:02 UTC, loqimean commented on app/views/books/_form.html.erb
> +<%= simple_form_for @book,  url: (@book.new_record? ? books_path : book_path(@book)), defaults: { input_html: { class: 'form_input' } }, html: { class: 'contents' } do |form| %>
?

2023-10-29 15:02 UTC, loqimean commented on app/views/books/_form.html.erb
> +  <%= form.error_notification %>
а це навіщо?

2023-10-29 15:02 UTC, loqimean commented on app/views/books/_form.html.erb
> +  <%= form.error_notification %>
не тре того

2023-10-29 15:02 UTC, loqimean commented on app/views/books/show.html.erb
> +
```suggestion
```

2023-10-29 15:02 UTC, loqimean commented on app/views/books/show.html.erb
> +      <%= button_to 'Destroy this book', book_path(@book), method: :delete, class: "btn-primary", data: {"turbo-confirm": "Are you sure you want to delete #{@book.title}?"}%>
```suggestion
      <%= button_to 'Destroy this book', book_path(@book), method: :delete, class: "btn-primary", data: { turbo_confirm: "Are you sure you want to delete #{@book.title}?" } %>
```

2023-10-29 15:02 UTC, loqimean commented on app/views/layouts/_flash.html.erb
> +<% if flash.any? %>
нема сенсу в цій перевірці, юо якщо їх не буде, то і й ітеруватися не буде по чому

2023-10-29 15:02 UTC, loqimean commented on config/routes.rb
> +  root "books#index"
рут зазвичай зверху

2023-10-29 15:02 UTC, loqimean commented on db/migrate/20231012072856_create_books.rb
> +      t.text :description
тобто у тебе може бути рекорд без жодного поля?))

2023-10-29 15:02 UTC, loqimean commented on db/migrate/20231014204002_add_not_null_constraint_to_books.rb
> +    change_column_null :books, :description, false
якщо це в одному ПР-і то, можеш спокійно ролбекати міграцію і правити її, а не створювати нову

2023-10-29 15:02 UTC, loqimean commented on spec/helpers/books_helper_spec.rb
навіщо тобі пустий файл?))

2023-10-29 15:02 UTC, loqimean commented on spec/models/book_spec.rb
> +    it { is_expected.not_to allow_value("a").for(:description) }
не бачу сенсу в цій валідації, бо міграції зверху те ж саме роблять)

2023-10-29 15:02 UTC, loqimean commented on spec/models/book_spec.rb
> +    it { is_expected.to allow_value(1234567890).for(:isbn) }
а де валідація на негативний кейс?))

2023-10-29 15:02 UTC, loqimean commented on spec/models/book_spec.rb
> +    end
`.to be_persisted`

2023-10-29 15:02 UTC, loqimean commented on spec/models/book_spec.rb
> +  let(:invalid_book) { build(:book, title: "", author: "Author Name", description: "Description", isbn: "1234567890") }
тут достатньо лише одного не валідного поля, а також бажано використати трейт для того

2023-10-29 15:02 UTC, loqimean commented on spec/models/book_spec.rb
> +    end
а це навіщо)

2023-10-29 15:02 UTC, loqimean commented on spec/requests/books_spec.rb
> +      create(:book, valid_attributes)
ну камон, у тебе для того є `let!`)

2023-10-29 15:02 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
```suggestion
      get books_url

      expect(response).to be_successful
```

2023-10-29 15:02 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
і де перевірка на наявність контенту на сторінці, який мав туди дійти?) я про рекорд

2023-10-29 15:02 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to be_successful
те ж і в інших тестах

2023-10-29 15:02 UTC, loqimean commented on spec/requests/books_spec.rb
> +        expect(response).to redirect_to(book_url(Book.last))
```suggestion
        end.to change(Book, :count).by(1)

        expect(response).to redirect_to(book_url(Book.last))
```

2023-10-29 15:02 UTC, loqimean commented on spec/requests/books_spec.rb
> +        expect(response).to redirect_to(book_url(Book.last))
а де перевірка на флеш? з чого б це ти впевнена, що Book.last поверне тобі саме ТВІЙ рекорд?)) я б не ризикував, бо саме так і появляються flascki-тести

2023-10-29 15:02 UTC, loqimean commented on spec/requests/books_spec.rb
> +        end.to change(Book, :count).by(0)
```suggestion
        end.not_to change(Book, :count)

```

2023-10-29 15:02 UTC, loqimean commented on spec/requests/books_spec.rb
> +        expect {
багатостроковий блок

2023-10-29 15:07 UTC, Natali-Kotelnitska commented on app/controllers/books_controller.rb
> +    flash.now[:warning] = "We have exactly #{@books.size} books available."
fixed

2023-10-29 15:08 UTC, Natali-Kotelnitska commented on app/controllers/books_controller.rb
> +      render :new, status: :unprocessable_entity
Done.

2023-10-29 15:08 UTC, Natali-Kotelnitska commented on app/controllers/books_controller.rb
> +      render :edit, status: :unprocessable_entity
Done.

2023-10-29 15:09 UTC, Natali-Kotelnitska commented on app/controllers/books_controller.rb
> +    @book.destroy
Done.

2023-10-29 17:50 UTC, Natali-Kotelnitska commented on app/controllers/application_controller.rb
> +  add_flash_types :error, :warning, :info
Видалила.

2023-10-29 18:03 UTC, Natali-Kotelnitska commented on spec/requests/books_spec.rb
> +      create(:book, valid_attributes)
Виправила, не потрібно створювати знов, оскільки є let!.

2023-10-29 19:44 UTC, Natali-Kotelnitska commented on app/views/books/_form.html.erb
> +  <%= form.error_notification %>
Fixed.

2023-10-29 19:46 UTC, Natali-Kotelnitska commented on app/views/books/show.html.erb
> +      <%= button_to 'Destroy this book', book_path(@book), method: :delete, class: "btn-primary", data: {"turbo-confirm": "Are you sure you want to delete #{@book.title}?"}%>
Done.

2023-10-29 19:48 UTC, Natali-Kotelnitska commented on app/views/layouts/_flash.html.erb
> +<% if flash.any? %>
Done.

2023-10-29 19:53 UTC, Natali-Kotelnitska commented on config/routes.rb
> +  root "books#index"
Виправила.

2023-10-29 19:56 UTC, Natali-Kotelnitska commented on db/migrate/20231012072856_create_books.rb
> +      t.text :description
Додала через міграцію. Вже знаю що можна правити цю, не обовязково додавати нову міграцію.

2023-10-29 19:59 UTC, Natali-Kotelnitska commented on spec/helpers/books_helper_spec.rb
Видалила.

2023-10-30 20:26 UTC, Natali-Kotelnitska commented on app/views/books/show.html.erb
> +
Done

2023-10-30 20:28 UTC, Natali-Kotelnitska commented on spec/models/book_spec.rb
> +    it { is_expected.not_to allow_value("a").for(:description) }
Ok.

2023-10-30 21:47 UTC, Natali-Kotelnitska commented on spec/models/book_spec.rb
> +    it { is_expected.to allow_value(1234567890).for(:isbn) }
Added.

2023-10-30 21:49 UTC, Natali-Kotelnitska commented on spec/models/book_spec.rb
> +    end
Fixed.

2023-10-30 22:03 UTC, Natali-Kotelnitska commented on spec/models/book_spec.rb
> +  let(:invalid_book) { build(:book, title: "", author: "Author Name", description: "Description", isbn: "1234567890") }
Added trait to factory.

2023-10-30 22:03 UTC, Natali-Kotelnitska commented on spec/models/book_spec.rb
> +    end
Deleted.

2023-10-30 22:43 UTC, Natali-Kotelnitska commented on spec/requests/books_spec.rb
> +        expect(response).to redirect_to(book_url(Book.last))
Fixed.

2023-10-30 22:44 UTC, Natali-Kotelnitska commented on spec/requests/books_spec.rb
> +        end.to change(Book, :count).by(0)
Fixed.

2023-11-02 08:09 UTC, loqimean requested changes

2023-11-02 08:09 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +@import "tailwindcss/utilities";
це має бути зверху і розділи новою строкою

2023-11-02 08:09 UTC, loqimean commented on app/assets/stylesheets/book_list.css
> +
```suggestion
```

2023-11-02 08:09 UTC, loqimean commented on app/assets/stylesheets/book_list.css
> +
```suggestion
```

2023-11-02 08:09 UTC, loqimean commented on app/assets/stylesheets/button.css
> +
```suggestion
```

2023-11-02 08:09 UTC, loqimean commented on app/assets/stylesheets/button.css
> +
```suggestion
```

2023-11-02 08:09 UTC, loqimean commented on app/assets/stylesheets/button.css
> +
і так у всіх файлах

2023-11-02 08:09 UTC, loqimean commented on app/controllers/books_controller.rb
> +
```suggestion
```

2023-11-02 08:09 UTC, loqimean commented on app/controllers/books_controller.rb
> +    status: :see_other
```suggestion
    redirect_to books_path, notice: "Book was successfully destroyed.", status: :see_other
```

2023-11-02 08:09 UTC, loqimean commented on app/helpers/application_helper.rb
> +end
видаляй

2023-11-02 08:09 UTC, loqimean commented on app/views/books/_form.html.erb
> +
```suggestion
```

2023-11-02 08:09 UTC, loqimean commented on db/migrate/20231031211245_create_books.rb
> +      t.string :isbn
а це не має бути присутнє завжди?

2023-11-02 08:09 UTC, loqimean commented on spec/factories/books.rb
> +
```suggestion
```

2023-11-02 08:09 UTC, loqimean commented on spec/models/book_spec.rb
> +    it { is_expected.to allow_value(1234567890).for(:isbn) }
де едед?))

2023-11-02 08:09 UTC, loqimean commented on spec/models/book_spec.rb
> +
```suggestion
```

2023-11-02 08:09 UTC, loqimean commented on spec/requests/books_spec.rb
> +      get new_book_url
юзай `_path`

2023-11-02 08:09 UTC, loqimean commented on spec/requests/books_spec.rb
> +          .not_to change(Book, :count)
```suggestion
        expect { post books_url, params: invalid_params }.not_to change(Book, :count)
```

2023-11-02 08:09 UTC, loqimean commented on spec/requests/books_spec.rb
> +       .to change(Book, :count).by(-1)
```suggestion
      expect { delete book_url(book) }.to change(Book, :count).by(-1)
```

2023-11-02 08:09 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to have_http_status(303)
`be_redirect`

2023-11-02 08:12 UTC, Natali-Kotelnitska commented on app/assets/stylesheets/application.tailwind.css
> +@import "tailwindcss/utilities";
Done.

2023-11-02 08:12 UTC, Natali-Kotelnitska commented on app/assets/stylesheets/book_list.css
> +
Done.

2023-11-02 08:13 UTC, Natali-Kotelnitska commented on app/assets/stylesheets/book_list.css
> +
Done.

2023-11-02 08:13 UTC, Natali-Kotelnitska commented on app/assets/stylesheets/button.css
> +
Done.

2023-11-02 08:14 UTC, Natali-Kotelnitska commented on app/assets/stylesheets/button.css
> +
Done.

2023-11-02 08:15 UTC, Natali-Kotelnitska commented on app/controllers/books_controller.rb
> +
Done.

2023-11-02 08:16 UTC, Natali-Kotelnitska commented on app/controllers/books_controller.rb
> +    status: :see_other
Done.

2023-11-02 08:16 UTC, Natali-Kotelnitska commented on app/helpers/application_helper.rb
> +end
Done.

2023-11-02 08:17 UTC, Natali-Kotelnitska commented on app/views/books/_form.html.erb
> +
Done.

2023-11-02 08:22 UTC, Natali-Kotelnitska commented on spec/factories/books.rb
> +
Done.

2023-11-02 09:57 UTC, Natali-Kotelnitska commented on db/migrate/20231031211245_create_books.rb
> +      t.string :isbn
Done.

2023-11-02 13:05 UTC, Natali-Kotelnitska commented on spec/requests/books_spec.rb
> +      get new_book_url
Done.

2023-11-02 13:06 UTC, Natali-Kotelnitska commented on spec/requests/books_spec.rb
> +          .not_to change(Book, :count)
Done.

2023-11-02 13:07 UTC, Natali-Kotelnitska commented on spec/requests/books_spec.rb
> +       .to change(Book, :count).by(-1)
Done.

2023-11-02 13:11 UTC, Natali-Kotelnitska commented on spec/requests/books_spec.rb
> +      expect(response).to have_http_status(303)
Done.

2023-11-05 11:33 UTC, loqimean requested changes

2023-11-05 11:33 UTC, loqimean commented on app/assets/stylesheets/application.tailwind.css
> +@import './book_card.css';
Поміщай ці файли відразу в якійсь папці, наприклад ʼlayers'

2023-11-05 11:33 UTC, loqimean commented on app/controllers/books_controller.rb
> +    @book = collection.new(book_params)
Не треба на колекції, роби ініціалізацію на класі

2023-11-05 11:33 UTC, loqimean commented on spec/models/book_spec.rb
> +    it { is_expected.not_to allow_value("&1hn!").for(:isbn) }
Так у тебе ж те саме робить чуть вище шкода матчерс), ну та уважніше ж треба дивитися до того, що ти пишеш)

2023-11-05 11:33 UTC, loqimean commented on spec/requests/books_spec.rb
> +
```suggestion
```

2023-11-05 11:33 UTC, loqimean commented on spec/requests/books_spec.rb
> +  let!(:book) { FactoryBot.create(:book) }
Не треба клас передавати, все і без того працює)

2023-11-05 11:33 UTC, loqimean commented on spec/requests/books_spec.rb
> +      expect(response).to have_http_status(303)
Не дан))

2023-11-05 11:48 UTC, Natali-Kotelnitska commented on app/assets/stylesheets/application.tailwind.css
> +@import './book_card.css';
Перенесла.

2023-11-05 11:49 UTC, Natali-Kotelnitska commented on app/controllers/books_controller.rb
> +    @book = collection.new(book_params)
Виправила.

2023-11-05 11:55 UTC, Natali-Kotelnitska commented on spec/models/book_spec.rb
> +    it { is_expected.not_to allow_value("&1hn!").for(:isbn) }
Done.

2023-11-05 12:24 UTC, Natali-Kotelnitska commented on spec/requests/books_spec.rb
> +
Done.

2023-11-05 12:32 UTC, loqimean approved these changes

2023-11-05 13:10 UTC, merged